services:
  dns-base:
    dns:
      - 172.18.0.2  # AdGuard container IP (set static)
      - 1.1.1.1     # Cloudflare fallback
      - 8.8.8.8     # Google fallback
    dns_search:
      - homelab.local
