#!/bin/bash
# rclone Google Drive Setup Guide
# Run these commands step by step

echo "========================================="
echo "rclone Google Drive Configuration Guide"
echo "========================================="
echo ""
echo "Step 1: Start rclone configuration"
echo "Run: docker exec -it kopia rclone config"
echo ""
echo "Step 2: Follow these prompts:"
echo ""
echo "  n) New remote"
echo "  Name: gdrive-backups"
echo "  Storage: 15 (Google Drive)"
echo "  Client ID: (press Enter - leave blank)"
echo "  Client Secret: (press Enter - leave blank)"
echo "  Scope: 1 (Full access)"
echo "  Root folder: (press Enter - leave blank)"
echo "  Service Account: n (no)"
echo "  Advanced config: n (no)"
echo "  Use web browser to authenticate: n (NO - important!)"
echo ""
echo "Step 3: You'll get a URL like:"
echo "  https://accounts.google.com/o/oauth2/auth?..."
echo ""
echo "  COPY THIS URL and open in your browser"
echo "  Log in with your Google account"
echo "  Click 'Allow'"
echo "  Copy the code that appears"
echo "  Paste it back in the terminal"
echo ""
echo "Step 4: Continue:"
echo "  Team Drive: n (no)"
echo "  Confirm: y (yes)"
echo "  Quit: q"
echo ""
echo "========================================="
echo "Ready? Let's do this!"
echo "========================================="
