services:

  # CLOUDFLARE TUNNEL
  cloudflared:
    image: cloudflare/cloudflared:2024.12.2
    container_name: cloudflared
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - infrastructure_net
      - proxy_net
    security_opt:
      - no-new-privileges:true
    mem_limit: 128m
    mem_reservation: 32m
    cpus: "0.2"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  infrastructure_net:
    name: infrastructure_net
    external: true
  
  proxy_net:
    name: proxy_net
    external: true
